---
- name: Existing install
  stat:
    path: "/snap/bin/intellij-idea-community"
  register: install

- name: Install
  community.general.snap:
    name: intellij-idea-community
    classic: true
  become: true
  when: not install.stat.exists
