---
- name: Existing install
  stat:
    path: "/usr/bin/firefox"
  register: install

- name: Install
  ansible.builtin.package:
    name:
      - firefox
    state: latest
  become: true
  when: not install.stat.exists
