# check if mongodb-compass installed
- name: Check mongodb compass Installed
  shell: which mongodb-compass
  register: compass_check
  ignore_errors: yes

- name: Install mongodb compass
  shell: |
    wget https://downloads.mongodb.com/compass/mongodb-compass_1.31.3_amd64.deb
    dpkg --install /tmp/compass.deb
    rm -rf /tmp/compass.deb
  when: compass_check.rc == 1