---
- name: Existing install
  stat:
    path: "/snap/bin/postman"
  register: install

- name: Install
  community.general.snap:
    name: postman
    classic: true
  become: true
  when: not install.stat.exists

