- name: Install
  ansible.builtin.package:
    name:
      - gdebi
      - jq
      - gcc
      - perl
      - curl
      - software-properties-common
      - wget
      - ncdu
      - tree
      - apt-transport-https
      - ca-certificates
      - gnupg
      - python3-pip
      - make
      - git
      - bash-completion
      - gnupg-agent
      - flameshot
      - mtr
      - terminator
      - sqlite3
      - libcanberra-gtk-module
      - libcanberra-gtk3-module
      - nitrogen
      - ffmpeg
    state: latest
  become: true


