---
- name: Existing install
  stat:
    path: "/snap/bin/storage-explorer"
  register: install

- name: Install
  community.general.snap:
    name: storage-explorer
  become: true
  when: not install.stat.exists
