---
- name: Existing install
  stat:
    path: "/snap/bin/redis-desktop-manager"
  register: install

- name: Install
  community.general.snap:
    name: redis-desktop-manager
  become: true
  when: not install.stat.exists
