---
- name: Install
  ansible.builtin.package:
    name:
      - terminator
    state: latest
  become: true

- name: Config folder
  ansible.builtin.file:
    mode: "0755"
    path: "{{ ansible_user_dir }}/.config/terminator"
    state: directory

- name: Configuration
  ansible.builtin.template:
    dest: "{{ ansible_user_dir }}/.config/terminator/config"
    src: "config"
