---
- name: Existing install
  stat:
    path: "/usr/local/bin/terraform"
  register: install

- name: Install HashiCorp Key
  become: true
  apt_key:
    url: 'https://apt.releases.hashicorp.com/gpg'
    state: present
  when: not install.stat.exists

- name: Install HashiCorp Repository
  apt_repository:
    repo: "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
    state: present
  when: not install.stat.exists


# - name: Install mongodb compass
#   shell: |
#     sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
#     sudo apt-get update && sudo apt-get install terraform
#   when: compass_check.rc == 1



- name: "Update Repository cache"
  apt:
    update_cache: true
    cache_valid_time: 3600
    force_apt_get: true
  when: not install.stat.exists

- name: Install
  ansible.builtin.package:
    name:
      - terraform
    state: latest
  become: true
  when: not install.stat.exists

# - name: Creating Symbolic Link
#   shell:
#     cmd: sudo ln -snf {{ ansible_env.HOME }}/bin/terraform /usr/bin/terraform
#   when: not install.stat.exists
