---
- name: Existing install
  stat:
    path: "/usr/bin/batcat"
  register: batcat

- name: Install
  ansible.builtin.package:
    name:
      - batcat
    state: latest
  become: true
  when: not batcat.stat.exists


