---
- name: Install
  uri:
    url: "https://discordapp.com/api/download?platform=linux&format=deb"
    method: HEAD
  register: discord_package_result

- name: check if discord is already installed or needs update
  command: dpkg-query --showformat='${Version}' --show discord
  register: discord_installed
  failed_when: discord_installed.rc > 1
  changed_when: (discord_installed.rc == 1) or (discord_installed.stdout != (discord_package_result.url | regex_search('(\d\.\d\.\d)')))

- name: install or update discord
  apt:
    deb: "https://discordapp.com/api/download?platform=linux&format=deb"
  when: (discord_installed.rc == 1) or (discord_installed.stdout != (discord_package_result.url | regex_search('(\d\.\d\.\d)')))
  become: true
