---
- name: Existing install
  stat:
    path: "/usr/bin/docker"
  register: install

- name: Install
  ansible.builtin.package:
    name:
      - docker
      - docker-compose
    state: latest
  become: true
  when: not install.stat.exists

- name: Enable service
  ansible.builtin.systemd:
    enabled: true
    name: docker
    state: started
  become: true

- name: Add to group
  ansible.builtin.user:
    append: true
    groups: docker
    name: "{{ ansible_env['USER'] }}"
  become: true

- name: Copy daemon.json
  ansible.builtin.template:
    dest: "/etc/docker/daemon.json"
    src: "daemon.json"
  become: true
  notify: restart_docker
