- name: Install Microsoft Key
  become: true
  apt_key:
    url: 'https://packages.microsoft.com/keys/microsoft.asc'
    state: present

- name: Install VSCode Repository
  become: true
  apt_repository:
    repo: 'deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main'
    state: present
    filename: vscode

- name: Install
  ansible.builtin.package:
    name:
      - code
    state: latest
  become: true

- name: Install Virtual Studio Code Extensions
  shell:
    cmd: code --install-extension '{{ item }}' 
  loop: 
    - ms-python.python
    - hashicorp.terraform
    - gruntfuggly.todo-tree
    - redhat.vscode-yaml
    - vscode-icons-team.vscode-icons
