---
- name: Existing install
  stat:
    path: "/usr/bin/code"
  register: code

- name: Install Microsoft Key
  become: true
  apt_key:
    url: 'https://packages.microsoft.com/keys/microsoft.asc'
    state: present
  when: not code.stat.exists

- name: Install VSCode Repository
  become: true
  apt_repository:
    repo: 'deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main'
    state: present
    filename: vscode
  when: not code.stat.exists

- name: Install
  ansible.builtin.package:
    name:
      - code
    state: latest
  become: true
  when: not code.stat.exists

- name: Install Virtual Studio Code Extensions
  shell:
    cmd: code --install-extension '{{ item }}' 
  loop: 
    - ms-python.python
    - naumovs.color-highlight
    - hashicorp.terraform
    - gruntfuggly.todo-tree
    - redhat.vscode-yaml
    - vscode-icons-team.vscode-icons
    - foxundermoon.shell-format
    - octref.vetur
    - bungcip.better-toml
    - alexcvzz.vscode-sqlite
    - dongli.python-preview
    - njpwerner.autodocstring
    - LittleFoxTeam.vscode-python-test-adapter
    - emmanuelbeziat.vscode-great-icons
