---
- name: Existing install
  stat:
    path: "/usr/bin/batcat"
  register: install

- name: Install
  ansible.builtin.package:
    name:
      - bat
    state: latest
  become: true
  when: not install.stat.exists


